spring.application.name=warehousesystem



spring.datasource.url=jdbc:postgresql://localhost:5432/warehousesystem
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true