
spring.application.name=warehousesystem

spring.datasource.url=jdbc:postgresql://localhost:5432/warehousesystem
spring.datasource.username=postgres
spring.datasource.password=ROOT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.app.jwtSecret=mySecretKey1pjihjubhbdvfeeygJNAMInydinixjsxmcn
spring.app.jwtExpirationMs=3600000
spring.app.jwtCookieName=WAREHOUSESYSTEMJWT
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
frontend.url=http://localhost:5173/